package net.ahmed.customer_service.web;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-08-28T17:08:43.043+01:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://web.customer_service.ahmed.net/", name = "CustomerSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerSoapService {

    @WebMethod
    @RequestWrapper(localName = "getCustomerById", targetNamespace = "http://web.customer_service.ahmed.net/", className = "net.ahmed.customer_service.web.GetCustomerById")
    @ResponseWrapper(localName = "getCustomerByIdResponse", targetNamespace = "http://web.customer_service.ahmed.net/", className = "net.ahmed.customer_service.web.GetCustomerByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public net.ahmed.customer_service.web.Customer getCustomerById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "customersList", targetNamespace = "http://web.customer_service.ahmed.net/", className = "net.ahmed.customer_service.web.CustomersList")
    @ResponseWrapper(localName = "customersListResponse", targetNamespace = "http://web.customer_service.ahmed.net/", className = "net.ahmed.customer_service.web.CustomersListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<net.ahmed.customer_service.web.Customer> customersList()
;

    @WebMethod
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://web.customer_service.ahmed.net/", className = "net.ahmed.customer_service.web.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://web.customer_service.ahmed.net/", className = "net.ahmed.customer_service.web.SaveCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public net.ahmed.customer_service.web.Customer saveCustomer(

        @WebParam(name = "customer", targetNamespace = "")
        net.ahmed.customer_service.web.CustomerReq customer
    );
}
